include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ChargingInterruptedHapticPreferences
ChargingInterruptedHapticPreferences_FILES = CIHRootListController.m
ChargingInterruptedHapticPreferences_FRAMEWORKS = UIKit
ChargingInterruptedHapticPreferences_PRIVATE_FRAMEWORKS = Preferences
ChargingInterruptedHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
ChargingInterruptedHapticPreferences_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
