name: NextJob
options:
  bundleIdPrefix: com.nextsolution
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.7"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: "NO"
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0.2"
    CURRENT_PROJECT_VERSION: "3"
  configs:
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule
      ENABLE_TESTABILITY: "NO"
targets:
  NextJob:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - README.md
          - Patches
          - Scripts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nextsolution.nextjob
        PRODUCT_NAME: Next Job
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: "NO"
    scheme:
      shared: true
      gatherCoverageData: false
