include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = NextHomeLockPreferences
NextHomeLockPreferences_FILES = NHLRootListController.m
NextHomeLockPreferences_FRAMEWORKS = UIKit
NextHomeLockPreferences_INSTALL_PATH = /Library/PreferenceBundles
NextHomeLockPreferences_RESOURCE_DIRS = Resources
NextHomeLockPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
NextHomeLockPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
