include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FullChargeHapticPreferences
FullChargeHapticPreferences_FILES = FCHRootListController.m
FullChargeHapticPreferences_FRAMEWORKS = UIKit
FullChargeHapticPreferences_PRIVATE_FRAMEWORKS = Preferences
FullChargeHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
FullChargeHapticPreferences_CFLAGS = -fobjc-arc -Wno-nullability-completeness
FullChargeHapticPreferences_LDFLAGS = -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
