include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = WiFiDropHapticPreferences
WiFiDropHapticPreferences_FILES = WDHRootListController.m
WiFiDropHapticPreferences_FRAMEWORKS = UIKit
WiFiDropHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
WiFiDropHapticPreferences_RESOURCE_DIRS = Resources
WiFiDropHapticPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
WiFiDropHapticPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
