include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ScreenshotHapticPreferences
ScreenshotHapticPreferences_FILES = SSHRootListController.m
ScreenshotHapticPreferences_FRAMEWORKS = UIKit
ScreenshotHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
ScreenshotHapticPreferences_RESOURCE_DIRS = Resources
ScreenshotHapticPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
ScreenshotHapticPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
