import PhotosUI
import SwiftUI
import UIKit

struct AutomationStatusBadge:View{let status:AutomationStatus;var body:some View{Label(status.title,systemImage:status.symbol).font(.caption2.bold()).foregroundStyle(status.color).padding(.horizontal,8).padding(.vertical,5).background(status.color.opacity(0.14),in:Capsule())}}
struct AutomationModeBadge:View{let mode:AutomationDeliveryMode;var body:some View{Label(mode.title,systemImage:mode.symbol).font(.caption2.bold()).foregroundStyle(.secondary).lineLimit(1)}}
struct AutomationMediaView:View{let url:URL?;var size:CGFloat=56;var body:some View{Group{if let url,let image=UIImage(contentsOfFile:url.path){Image(uiImage:image).resizable().scaledToFill()}else{ZStack{Color.nextCard;Image(systemName:"photo.fill").foregroundStyle(.secondary)}}}.frame(width:size,height:size).clipShape(RoundedRectangle(cornerRadius:13))}}
struct AutomationCard:View{let item:SocialAutomation;let account:String?;let mediaURL:URL?;var body:some View{HStack(spacing:13){if item.media != nil{AutomationMediaView(url:mediaURL)}else{RoundedRectangle(cornerRadius:13).fill(item.platform.color.opacity(0.14)).frame(width:56,height:56).overlay(Image(systemName:item.platform.symbol).font(.title2.bold()).foregroundStyle(item.platform.color))};VStack(alignment:.leading,spacing:5){Text(item.title).font(.headline).lineLimit(2);Text(item.scheduledAt.compactDateTime).font(.caption).foregroundStyle(.secondary);if let account{Text(account).font(.caption2).foregroundStyle(.secondary)}};Spacer();VStack(alignment:.trailing,spacing:8){AutomationStatusBadge(status:item.status);AutomationModeBadge(mode:item.deliveryMode)}}.padding(14).background(LinearGradient(colors:[item.platform.color.opacity(0.1),Color.nextCard.opacity(0.98)],startPoint:.leading,endPoint:.trailing),in:RoundedRectangle(cornerRadius:18)).overlay(RoundedRectangle(cornerRadius:18).stroke(item.platform.color.opacity(0.2),lineWidth:1))}}
struct ActivityViewController:UIViewControllerRepresentable{let items:[Any];func makeUIViewController(context:Context)->UIActivityViewController{UIActivityViewController(activityItems:items,applicationActivities:nil)};func updateUIViewController(_ controller:UIActivityViewController,context:Context){}}
struct IdentifiedAutomationID:Identifiable,Equatable{let id:UUID}
enum AddFlow:String,Identifiable{case reminder,automation;var id:String{rawValue}}

enum AutomationListFilter:String,CaseIterable,Identifiable{case all,scheduled,attention,history;var id:String{rawValue};var title:String{switch self{case .all:return"All";case .scheduled:return"Scheduled";case .attention:return"Attention";case .history:return"History"}}}

struct AutomationsView:View{
 @EnvironmentObject private var store:AutomationStore;@State private var filter:AutomationListFilter = .all;@State private var platform:AutomationPlatform?;@State private var search="";@State private var adding=false
 private var list:[SocialAutomation]{store.automations.filter{a in let s=search.isEmpty || a.title.localizedCaseInsensitiveContains(search) || a.contentText.localizedCaseInsensitiveContains(search);let p=platform == nil || a.platform == platform;let f:Bool;switch filter{case .all:f=true;case .scheduled:f=[.scheduled,.processing].contains(a.status);case .attention:f=[.needsSetup,.awaitingApproval,.failed].contains(a.status);case .history:f=a.status.isFinished};return s&&p&&f}.sorted{$0.status.isFinished == $1.status.isFinished ? ($0.status.isFinished ? ($0.completedAt ?? $0.updatedAt)>($1.completedAt ?? $1.updatedAt):$0.scheduledAt<$1.scheduledAt):!$0.status.isFinished}}
 var body:some View{ScrollView{LazyVStack(spacing:14){header;filters;platforms;if list.isEmpty{EmptyStateView(icon:"paperplane.circle",title:"No automations found",message:"Schedule a WhatsApp message, Instagram post or Story, or an X post.")}else{ForEach(list){a in NavigationLink(value:a.id){AutomationCard(item:a,account:store.account(a.accountID)?.displayName,mediaURL:store.mediaURL(a))}.buttonStyle(.plain).contextMenu{Button{store.duplicate(a)}label:{Label("Duplicate",systemImage:"plus.square.on.square")};if a.status == .paused{Button{store.resume(a)}label:{Label("Resume",systemImage:"play.circle")}}else if !a.status.isFinished{Button{store.pause(a)}label:{Label("Pause",systemImage:"pause.circle")}};Button(role:.destructive){store.delete(a)}label:{Label("Delete",systemImage:"trash")}}}}}.padding(.horizontal,16).padding(.bottom,24)}.background(Color.nextBackground.ignoresSafeArea()).navigationTitle("Automations").navigationBarTitleDisplayMode(.inline).searchable(text:$search,prompt:"Search automations").toolbar{ToolbarItem(placement:.navigationBarLeading){NavigationLink{AutomationConnectionsView()}label:{Image(systemName:"network.badge.shield.half.filled")}};ToolbarItem(placement:.navigationBarTrailing){Button{adding=true}label:{Image(systemName:"plus")}}}.navigationDestination(for:UUID.self){AutomationDetailView(automationID:$0)}.sheet(isPresented:$adding){NavigationStack{AutomationEditorView(automation:nil)}.environmentObject(store)}.onAppear{store.refreshDueStatuses()}}
 private var header:some View{HStack{VStack(alignment:.leading,spacing:4){Text("Scheduled publishing").font(.title2.bold());Text("\(store.active.count) active").font(.subheadline).foregroundStyle(.secondary)};Spacer();Image(systemName:"paperplane.fill").font(.title3).foregroundStyle(.nextOrange).frame(width:48,height:48).background(Color.nextOrange.opacity(0.15),in:Circle())}.padding(.top,8)}
 private var filters:some View{ScrollView(.horizontal,showsIndicators:false){HStack(spacing:8){ForEach(AutomationListFilter.allCases){x in Button{filter=x}label:{Text(x.title).font(.subheadline.bold()).foregroundStyle(filter==x ? Color.white:Color.primary).padding(.horizontal,14).padding(.vertical,9).background(Capsule().fill(filter==x ? Color.nextOrange:Color.nextCard))}.buttonStyle(.plain)}}}}
 private var platforms:some View{ScrollView(.horizontal,showsIndicators:false){HStack(spacing:8){Button{platform=nil}label:{Label("All",systemImage:"square.grid.2x2.fill").font(.subheadline.bold()).foregroundStyle(platform==nil ? Color.white:Color.primary).padding(.horizontal,12).padding(.vertical,9).background(Capsule().fill(platform==nil ? Color.nextOrange:Color.nextCard))}.buttonStyle(.plain);ForEach(AutomationPlatform.allCases){x in Button{platform=x}label:{Label(x.shortTitle,systemImage:x.symbol).font(.subheadline.bold()).foregroundStyle(platform==x ? Color.white:x.color).padding(.horizontal,12).padding(.vertical,9).background(Capsule().fill(platform==x ? x.color:Color.nextCard))}.buttonStyle(.plain)}}}}
}

struct AutomationEditorView:View{
 @Environment(\.dismiss) private var dismiss;@EnvironmentObject private var store:AutomationStore;let automation:SocialAutomation?
 @State private var title:String;@State private var platform:AutomationPlatform;@State private var mode:AutomationDeliveryMode;@State private var date:Date;@State private var repeatRule:AutomationRepeat;@State private var alerts:Set<AutomationAlertOffset>;@State private var accountID:UUID?;@State private var recipient:String;@State private var text:String;@State private var altText:String;@State private var link:String;@State private var retry:Bool;@State private var maxRetries:Int;@State private var picker:PhotosPickerItem?;@State private var imageData:Data?;@State private var removeMedia=false;@State private var loading=false;@State private var photoError=false
 init(automation:SocialAutomation?){self.automation=automation;_title=State(initialValue:automation?.title ?? "");_platform=State(initialValue:automation?.platform ?? .whatsapp);_mode=State(initialValue:automation?.deliveryMode ?? .approval);_date=State(initialValue:automation?.scheduledAt ?? Date().addingTimeInterval(3600));_repeatRule=State(initialValue:automation?.repeatRule ?? .never);_alerts=State(initialValue:automation?.alertOffsets ?? [.atTime]);_accountID=State(initialValue:automation?.accountID);_recipient=State(initialValue:automation?.recipient ?? "");_text=State(initialValue:automation?.contentText ?? "");_altText=State(initialValue:automation?.altText ?? "");_link=State(initialValue:automation?.linkURL ?? "");_retry=State(initialValue:automation?.retryEnabled ?? true);_maxRetries=State(initialValue:automation?.maxRetries ?? 3)}
 private var accounts:[AutomationAccount]{store.compatible(platform)};private var canSave:Bool{!title.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty && (!text.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty || imageData != nil || (automation?.media != nil && !removeMedia)) && (platform != .whatsapp || !recipient.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty) && date > Date().addingTimeInterval(-60)}
 var body:some View{ScrollView{VStack(spacing:20){platformSection;fieldSection;scheduleSection;modeSection;accountSection;contentSection;photoSection;retrySection;Button(automation==nil ? "Create Automation":"Save Changes"){save()}.buttonStyle(OrangeActionButtonStyle()).disabled(!canSave).opacity(canSave ? 1:0.5)}.padding(16).padding(.bottom,30)}.background(Color.nextBackground.ignoresSafeArea()).navigationTitle(automation==nil ? "New Automation":"Edit Automation").navigationBarTitleDisplayMode(.inline).toolbar{ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}}}.onChange(of:platform){p in if let accountID,!store.compatible(p).contains(where:{$0.id==accountID}){self.accountID=nil}}.onChange(of:picker){if let item=$0{Task{await load(item)}}}.alert("The image could not be loaded.",isPresented:$photoError){Button("OK",role:.cancel){}}}
 private var platformSection:some View{VStack(alignment:.leading,spacing:12){SectionHeader(title:"Platform");LazyVGrid(columns:[GridItem(.adaptive(minimum:135),spacing:10)],spacing:10){ForEach(AutomationPlatform.allCases){x in Button{platform=x}label:{VStack(spacing:7){Image(systemName:x.symbol).font(.title2);Text(x.title).font(.caption.bold()).multilineTextAlignment(.center)}.foregroundStyle(platform==x ? Color.white:x.color).frame(maxWidth:.infinity,minHeight:74).background(RoundedRectangle(cornerRadius:14).fill(platform==x ? x.color:x.color.opacity(0.12)))}.buttonStyle(.plain)}}}}
 private var fieldSection:some View{VStack(alignment:.leading,spacing:12){SectionHeader(title:"Automation");TextField("Automation title",text:$title).padding(14).nextCard();if platform == .whatsapp{TextField("Recipient number with country code",text:$recipient).keyboardType(.phonePad).padding(14).nextCard()}}}
 private var scheduleSection:some View{VStack(alignment:.leading,spacing:12){SectionHeader(title:"Schedule");DatePicker("Date and time",selection:$date,in:Date()...,displayedComponents:[.date,.hourAndMinute]).padding(14).nextCard();Menu{ForEach(AutomationRepeat.allCases){x in Button(x.title){repeatRule=x}}}label:{row("repeat","Repeat",repeatRule.title)}.buttonStyle(.plain);LazyVGrid(columns:[GridItem(.adaptive(minimum:90),spacing:9)],spacing:9){ForEach(AutomationAlertOffset.allCases){x in Button{alerts.contains(x) ? alerts.remove(x):alerts.insert(x)}label:{Label(x.title,systemImage:alerts.contains(x) ? "checkmark.circle.fill":"bell").font(.caption.bold()).foregroundStyle(alerts.contains(x) ? Color.white:Color.primary).frame(maxWidth:.infinity).padding(.vertical,11).background(RoundedRectangle(cornerRadius:12).fill(alerts.contains(x) ? Color.nextOrange:Color.nextCard))}.buttonStyle(.plain)}}}}
 private var modeSection:some View{VStack(alignment:.leading,spacing:12){SectionHeader(title:"Delivery Mode");ForEach(AutomationDeliveryMode.allCases){x in Button{mode=x}label:{HStack(alignment:.top,spacing:12){Image(systemName:x.symbol).foregroundStyle(mode==x ? .nextOrange:.secondary).frame(width:28);VStack(alignment:.leading,spacing:4){Text(x.title).font(.headline);Text(x.explanation).font(.caption).foregroundStyle(.secondary).multilineTextAlignment(.leading)};Spacer();Image(systemName:mode==x ? "checkmark.circle.fill":"circle").foregroundStyle(mode==x ? .nextOrange:.secondary)}.padding(14).nextCard()}.buttonStyle(.plain)};if mode == .automaticCloud{Label(store.cloudConfiguration.isConfigured ? "Automation server configured":"Automation server setup required",systemImage:store.cloudConfiguration.isConfigured ? "checkmark.shield.fill":"exclamationmark.triangle.fill").font(.caption.bold()).foregroundStyle(store.cloudConfiguration.isConfigured ? .green:.orange)}}}
 private var accountSection:some View{VStack(alignment:.leading,spacing:12){SectionHeader(title:"Account",trailing:"Settings");if accounts.isEmpty{NavigationLink{AutomationConnectionsView()}label:{row("person.badge.plus","Add compatible account",platform.shortTitle)}.buttonStyle(.plain)}else{Menu{Button("No account"){accountID=nil};ForEach(accounts){a in Button(a.displayName){accountID=a.id}}}label:{row("person.crop.circle.fill","Publishing account",store.account(accountID)?.displayName ?? "Select account")}.buttonStyle(.plain)};if platform == .instagramStory,let a=store.account(accountID),a.accountType != .instagramBusiness{Text("Automatic Instagram Stories require an Instagram Business account.").font(.caption).foregroundStyle(.orange)}}}
 private var contentSection:some View{VStack(alignment:.leading,spacing:12){SectionHeader(title:platform.contentPrompt);TextEditor(text:$text).frame(minHeight:145).scrollContentBackground(.hidden).padding(10).nextCard();TextField("Optional link",text:$link).textInputAutocapitalization(.never).keyboardType(.URL).padding(14).nextCard();if platform != .whatsapp{TextField("Image alt text (optional)",text:$altText).padding(14).nextCard()};if platform == .xPost{Text("Text length: \(text.count) characters").font(.caption).foregroundStyle(text.count>280 ? .orange:.secondary)}}}
 private var photoSection:some View{VStack(alignment:.leading,spacing:12){SectionHeader(title:"Photo",trailing:"Optional");if let imageData,let i=UIImage(data:imageData){Image(uiImage:i).resizable().scaledToFill().frame(maxWidth:.infinity).frame(height:210).clipped().clipShape(RoundedRectangle(cornerRadius:18))}else if let a=automation,a.media != nil,!removeMedia,let u=store.mediaURL(a),let i=UIImage(contentsOfFile:u.path){Image(uiImage:i).resizable().scaledToFill().frame(maxWidth:.infinity).frame(height:210).clipped().clipShape(RoundedRectangle(cornerRadius:18))};PhotosPicker(selection:$picker,matching:.images){Label(loading ? "Loading…":"Choose Photo",systemImage:"photo.badge.plus").font(.headline).frame(maxWidth:.infinity).padding(.vertical,13).background(Color.nextCard,in:RoundedRectangle(cornerRadius:14))}.disabled(loading);if imageData != nil || (automation?.media != nil && !removeMedia){Button(role:.destructive){imageData=nil;picker=nil;removeMedia=true}label:{Label("Remove Photo",systemImage:"trash").frame(maxWidth:.infinity)}}}}
 private var retrySection:some View{VStack(alignment:.leading,spacing:12){SectionHeader(title:"Failure Handling");Toggle("Retry temporary failures",isOn:$retry).padding(14).nextCard();if retry{Stepper("Maximum retries: \(maxRetries)",value:$maxRetries,in:1...5).padding(14).nextCard()}}}
 private func row(_ icon:String,_ title:String,_ value:String)->some View{HStack{Image(systemName:icon).foregroundStyle(.nextOrange).frame(width:28);VStack(alignment:.leading,spacing:3){Text(title).font(.headline);Text(value).font(.caption).foregroundStyle(.secondary)};Spacer();Image(systemName:"chevron.up.chevron.down").font(.caption).foregroundStyle(.secondary)}.padding(14).nextCard()}
 private func load(_ item:PhotosPickerItem)async{loading=true;defer{loading=false};do{guard let d=try await item.loadTransferable(type:Data.self),let i=UIImage(data:d),let c=i.jpegData(compressionQuality:0.82),c.count<=10_000_000 else{throw AutomationError.mediaTooLarge};imageData=c;removeMedia=false}catch{photoError=true}}
 private func save(){let a=alerts.isEmpty ? Set([AutomationAlertOffset.atTime]):alerts;if var x=automation{x.title=title.trimmingCharacters(in:.whitespacesAndNewlines);x.platform=platform;x.deliveryMode=mode;x.scheduledAt=date;x.timeZoneIdentifier=TimeZone.current.identifier;x.repeatRule=repeatRule;x.alertOffsets=a;x.accountID=accountID;x.recipient=recipient.trimmingCharacters(in:.whitespacesAndNewlines);x.contentText=text.trimmingCharacters(in:.whitespacesAndNewlines);x.altText=altText.trimmingCharacters(in:.whitespacesAndNewlines);x.linkURL=link.trimmingCharacters(in:.whitespacesAndNewlines);x.retryEnabled=retry;x.maxRetries=maxRetries;store.update(x,image:imageData,removeMedia:removeMedia)}else{store.add(.init(title:title.trimmingCharacters(in:.whitespacesAndNewlines),platform:platform,deliveryMode:mode,scheduledAt:date,repeatRule:repeatRule,alertOffsets:a,accountID:accountID,recipient:recipient.trimmingCharacters(in:.whitespacesAndNewlines),contentText:text.trimmingCharacters(in:.whitespacesAndNewlines),altText:altText.trimmingCharacters(in:.whitespacesAndNewlines),linkURL:link.trimmingCharacters(in:.whitespacesAndNewlines),retryEnabled:retry,maxRetries:maxRetries),image:imageData)};dismiss()}
}

struct AutomationDetailView:View{
 @Environment(\.dismiss) private var dismiss;@EnvironmentObject private var store:AutomationStore;let automationID:UUID;@State private var editing=false;@State private var deleting=false;@State private var sharing=false;@State private var shareItems:[Any]=[];@State private var confirm=false;@State private var publishing=false
 private var item:SocialAutomation?{store.automation(automationID)}
 var body:some View{Group{if let a=item{ScrollView{VStack(spacing:18){header(a);content(a);details(a);actions(a);history(a)}.padding(16).padding(.bottom,28)}.background(Color.nextBackground.ignoresSafeArea()).navigationTitle("Automation Details").navigationBarTitleDisplayMode(.inline).toolbar{ToolbarItemGroup(placement:.navigationBarTrailing){Button{editing=true}label:{Image(systemName:"pencil")};Button(role:.destructive){deleting=true}label:{Image(systemName:"trash")}}}.sheet(isPresented:$editing){NavigationStack{AutomationEditorView(automation:a)}.environmentObject(store)}.sheet(isPresented:$sharing,onDismiss:{confirm=true}){ActivityViewController(items:shareItems)}.confirmationDialog(a.platform == .whatsapp ? "Was the message sent?":"Was the content published?",isPresented:$confirm,titleVisibility:.visible){Button(a.platform == .whatsapp ? "Yes, Mark Sent":"Yes, Mark Published"){store.markAssistedComplete(a)};Button("Not Yet",role:.cancel){}}.confirmationDialog("Delete this automation?",isPresented:$deleting,titleVisibility:.visible){Button("Delete",role:.destructive){store.delete(a);dismiss()}}}else{EmptyStateView(icon:"questionmark.circle",title:"Automation not found",message:"This automation may have been deleted.")}}.onAppear{store.refreshDueStatuses()}}
 private func header(_ a:SocialAutomation)->some View{VStack(spacing:14){Image(systemName:a.platform.symbol).font(.system(size:34,weight:.bold)).foregroundStyle(a.platform.color).frame(width:82,height:82).background(a.platform.color.opacity(0.14),in:Circle());Text(a.title).font(.title2.bold()).multilineTextAlignment(.center);HStack{AutomationStatusBadge(status:a.status);AutomationModeBadge(mode:a.deliveryMode)};Text(a.scheduledAt.formatted(date:.long,time:.shortened)).font(.subheadline).foregroundStyle(.secondary)}.frame(maxWidth:.infinity).padding(20).nextCard()}
 private func content(_ a:SocialAutomation)->some View{VStack(alignment:.leading,spacing:14){SectionHeader(title:"Prepared Content");if a.media != nil{AutomationMediaView(url:store.mediaURL(a),size:220).frame(maxWidth:.infinity)};if !a.contentText.isEmpty{Text(a.contentText).textSelection(.enabled)};if !a.linkURL.isEmpty{Label(a.linkURL,systemImage:"link").font(.caption).foregroundStyle(.blue).textSelection(.enabled)};if a.platform == .whatsapp{line("person.fill","Recipient",a.recipient)};if !a.altText.isEmpty{line("text.bubble","Alt text",a.altText)}}.padding(16).nextCard()}
 private func details(_ a:SocialAutomation)->some View{VStack(spacing:0){line("clock.fill","Scheduled",a.scheduledAt.formatted(date:.abbreviated,time:.shortened));Divider().opacity(0.2);line("repeat","Repeat",a.repeatRule.title);Divider().opacity(0.2);line("person.crop.circle","Account",store.account(a.accountID)?.displayName ?? "Not selected");if let e=a.lastError{Divider().opacity(0.2);line("exclamationmark.triangle.fill","Last Error",e)}}.nextCard()}
 @ViewBuilder private func actions(_ a:SocialAutomation)->some View{if !a.status.isFinished && a.status != .paused{VStack(spacing:12){if a.deliveryMode == .automaticCloud || (a.deliveryMode == .approval && store.cloudConfiguration.isConfigured && store.account(a.accountID)?.isReadyForAutomaticPublishing == true){Button{Task{publishing=true;await store.submit(a,publishNow:true);publishing=false}}label:{Label(publishing ? "Publishing…":(a.deliveryMode == .approval ? "Approve & Publish":"Publish Now"),systemImage:"cloud.fill")}.buttonStyle(OrangeActionButtonStyle()).disabled(publishing);Button{assisted(a)}label:{Label("Use Assisted Publishing",systemImage:"hand.tap.fill").frame(maxWidth:.infinity).padding(.vertical,13).background(Color.nextCard,in:RoundedRectangle(cornerRadius:14))}.buttonStyle(.plain)}else{Button{assisted(a)}label:{Label(a.platform == .whatsapp ? "Open WhatsApp / Share":"Open Share / Compose",systemImage:"paperplane.fill")}.buttonStyle(OrangeActionButtonStyle())};HStack{Button{store.duplicate(a)}label:{Label("Duplicate",systemImage:"plus.square.on.square").frame(maxWidth:.infinity).padding(.vertical,12).background(Color.nextCard,in:RoundedRectangle(cornerRadius:13))}.buttonStyle(.plain);Button{a.status == .paused ? store.resume(a):store.pause(a)}label:{Label(a.status == .paused ? "Resume":"Pause",systemImage:a.status == .paused ? "play.fill":"pause.fill").frame(maxWidth:.infinity).padding(.vertical,12).background(Color.nextCard,in:RoundedRectangle(cornerRadius:13))}.buttonStyle(.plain)}}}}
 @ViewBuilder private func history(_ a:SocialAutomation)->some View{if !a.history.isEmpty{VStack(alignment:.leading,spacing:12){SectionHeader(title:"History");ForEach(a.history.reversed()){h in HStack(alignment:.top,spacing:12){Image(systemName:h.status.symbol).foregroundStyle(h.status.color).frame(width:26);VStack(alignment:.leading,spacing:4){Text(h.status.title).font(.subheadline.bold());Text(h.date.formatted(date:.abbreviated,time:.shortened)).font(.caption).foregroundStyle(.secondary);if !h.comment.isEmpty{Text(h.comment).font(.subheadline)}};Spacer()}.padding(14).nextCard()}}}}
 private func line(_ icon:String,_ title:String,_ value:String)->some View{HStack(alignment:.top,spacing:12){Image(systemName:icon).foregroundStyle(.nextOrange).frame(width:24);VStack(alignment:.leading,spacing:4){Text(title).font(.caption).foregroundStyle(.secondary);Text(value).font(.subheadline.weight(.medium)).textSelection(.enabled)};Spacer()}.padding(14)}
 private func assisted(_ a:SocialAutomation){if let u=AssistedAutomationPublisher.url(a){UIApplication.shared.open(u){ok in if ok{confirm=true}else{present(a)}}}else{present(a)}};private func present(_ a:SocialAutomation){shareItems=AssistedAutomationPublisher.items(a,media:store.mediaData(a));if !shareItems.isEmpty{sharing=true}}
}

struct AutomationConnectionsView:View{
 @EnvironmentObject private var store:AutomationStore;@State private var endpoint="";@State private var key="";@State private var adding=false;@State private var selected:AutomationAccount?
 var body:some View{ScrollView{VStack(alignment:.leading,spacing:22){SectionHeader(title:"Automatic Scheduler");TextField("HTTPS server URL",text:$endpoint).textInputAutocapitalization(.never).keyboardType(.URL).padding(14).nextCard();SecureField("Scheduler API key",text:$key).padding(14).nextCard();HStack{Button("Save Securely"){store.saveCloud(endpoint:endpoint,key:key)}.buttonStyle(OrangeActionButtonStyle());Button{Task{await store.testCloud(endpoint:endpoint,key:key)}}label:{Image(systemName:store.isTesting ? "hourglass":"network").frame(width:46,height:46).background(Color.nextCard,in:RoundedRectangle(cornerRadius:14))}.buttonStyle(.plain)};if let m=store.connectionMessage{Text(m).font(.caption).foregroundStyle(.secondary)};Text("The scheduler receives automatic jobs immediately and runs them at the selected time. Use a trusted HTTPS service; social passwords are never stored in this app.").font(.caption).foregroundStyle(.secondary);SectionHeader(title:"Publishing Accounts",trailing:"No passwords");if store.accounts.isEmpty{Button{adding=true}label:{Label("Add WhatsApp, Instagram, or X account",systemImage:"person.badge.plus").font(.headline).frame(maxWidth:.infinity).padding(16).nextCard()}.buttonStyle(.plain)}else{ForEach(store.accounts){a in Button{selected=a}label:{HStack{Image(systemName:a.accountType.platform == .whatsapp ? "message.fill":a.accountType.platform == .instagram ? "camera.fill":"text.bubble.fill").font(.title3).foregroundStyle(.nextOrange).frame(width:32);VStack(alignment:.leading){Text(a.displayName).font(.headline);Text(a.accountType.title).font(.caption).foregroundStyle(.secondary)};Spacer();Image(systemName:a.isReadyForAutomaticPublishing ? "checkmark.shield.fill":"hand.tap.fill").foregroundStyle(a.isReadyForAutomaticPublishing ? .green:.orange)}.padding(14).nextCard()}.buttonStyle(.plain)}};SectionHeader(title:"Requirements");requirement("message.fill","WhatsApp","Automatic messages require WhatsApp Business Cloud. Personal WhatsApp uses Assisted mode.");requirement("camera.fill","Instagram","Posts require a Professional account. Automatic Stories require a Business account.");requirement("text.bubble.fill","X","Automatic posts require an X developer app and authenticated write access.")}.padding(16).padding(.bottom,30)}.background(Color.nextBackground.ignoresSafeArea()).navigationTitle("Automation Connections").navigationBarTitleDisplayMode(.inline).toolbar{ToolbarItem(placement:.navigationBarTrailing){Button{adding=true}label:{Image(systemName:"person.badge.plus")}}}.onAppear{endpoint=store.cloudEndpoint;key=store.cloudAPIKey}.sheet(isPresented:$adding){NavigationStack{AutomationAccountEditorView(account:nil)}.environmentObject(store)}.sheet(item:$selected){NavigationStack{AutomationAccountEditorView(account:$0)}.environmentObject(store)}}
 private func requirement(_ icon:String,_ title:String,_ text:String)->some View{HStack(alignment:.top,spacing:12){Image(systemName:icon).foregroundStyle(.nextOrange).frame(width:28);VStack(alignment:.leading,spacing:4){Text(title).font(.headline);Text(text).font(.caption).foregroundStyle(.secondary)};Spacer()}.padding(14).nextCard()}
}

struct AutomationAccountEditorView:View{
 @Environment(\.dismiss) private var dismiss;@EnvironmentObject private var store:AutomationStore;let account:AutomationAccount?;@State private var name:String;@State private var handle:String;@State private var remoteID:String;@State private var type:AutomationAccountType;@State private var automatic:Bool;@State private var deleting=false
 init(account:AutomationAccount?){self.account=account;_name=State(initialValue:account?.displayName ?? "");_handle=State(initialValue:account?.handleOrNumber ?? "");_remoteID=State(initialValue:account?.remoteAccountID ?? "");_type=State(initialValue:account?.accountType ?? .whatsappBusiness);_automatic=State(initialValue:account?.automaticPublishingEnabled ?? false)}
 var body:some View{ScrollView{VStack(alignment:.leading,spacing:18){TextField("Account label",text:$name).padding(14).nextCard();TextField("Handle or business number",text:$handle).textInputAutocapitalization(.never).padding(14).nextCard();Menu{ForEach(AutomationAccountType.allCases){x in Button(x.title){type=x}}}label:{HStack{Image(systemName:"person.crop.circle").foregroundStyle(.nextOrange);VStack(alignment:.leading){Text("Account type").font(.headline);Text(type.title).font(.caption).foregroundStyle(.secondary)};Spacer();Image(systemName:"chevron.up.chevron.down").font(.caption).foregroundStyle(.secondary)}.padding(14).nextCard()}.buttonStyle(.plain);TextField("Remote account ID from scheduler",text:$remoteID).textInputAutocapitalization(.never).padding(14).nextCard();Toggle("Enable automatic publishing",isOn:$automatic).padding(14).nextCard();Text("The remote ID refers to the OAuth-connected account on your scheduler. Never enter a social-media password here.").font(.caption).foregroundStyle(.secondary);Button(account==nil ? "Add Account":"Save Account"){save()}.buttonStyle(OrangeActionButtonStyle()).disabled(name.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty);if account != nil{Button(role:.destructive){deleting=true}label:{Label("Delete Account",systemImage:"trash").frame(maxWidth:.infinity)}}}.padding(16)}.background(Color.nextBackground.ignoresSafeArea()).navigationTitle(account==nil ? "Add Account":"Edit Account").navigationBarTitleDisplayMode(.inline).toolbar{ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}}}.confirmationDialog("Delete this account?",isPresented:$deleting,titleVisibility:.visible){Button("Delete",role:.destructive){if let account{store.deleteAccount(account)};dismiss()}}}
 private func save(){if var a=account{a.displayName=name.trimmingCharacters(in:.whitespacesAndNewlines);a.handleOrNumber=handle.trimmingCharacters(in:.whitespacesAndNewlines);a.remoteAccountID=remoteID.trimmingCharacters(in:.whitespacesAndNewlines);a.accountType=type;a.automaticPublishingEnabled=automatic;store.updateAccount(a)}else{store.addAccount(.init(displayName:name.trimmingCharacters(in:.whitespacesAndNewlines),handleOrNumber:handle.trimmingCharacters(in:.whitespacesAndNewlines),remoteAccountID:remoteID.trimmingCharacters(in:.whitespacesAndNewlines),accountType:type,automaticPublishingEnabled:automatic))};dismiss()}
}
