import Combine
import Foundation
import Security
import SwiftUI
import UIKit
import UserNotifications

struct AutomationPersistence {
    private let fm = FileManager.default
    private var folder: URL { let base=fm.urls(for:.applicationSupportDirectory,in:.userDomainMask)[0].appendingPathComponent("NextReminder",isDirectory:true); try? fm.createDirectory(at:base,withIntermediateDirectories:true); return base }
    private var dbURL: URL { folder.appendingPathComponent("NextReminderAutomations.json") }
    private var mediaFolder: URL { let url=folder.appendingPathComponent("AutomationMedia",isDirectory:true); try? fm.createDirectory(at:url,withIntermediateDirectories:true); return url }
    func load() throws -> AutomationDatabase { guard fm.fileExists(atPath:dbURL.path) else { return .init(automations:[],accounts:[]) }; let d=try Data(contentsOf:dbURL); let x=JSONDecoder(); x.dateDecodingStrategy = .iso8601; return try x.decode(AutomationDatabase.self,from:d) }
    func save(_ value: AutomationDatabase) throws { let e=JSONEncoder(); e.dateEncodingStrategy = .iso8601; e.outputFormatting=[.sortedKeys]; try e.encode(value).write(to:dbURL,options:.atomic) }
    func saveImage(_ data: Data) throws -> AutomationMediaAttachment { let name="\(UUID().uuidString).jpg"; try data.write(to:mediaFolder.appendingPathComponent(name),options:.atomic); return .init(fileName:name,byteCount:data.count) }
    func url(_ media: AutomationMediaAttachment) -> URL { mediaFolder.appendingPathComponent(media.fileName) }
    func data(_ media: AutomationMediaAttachment) -> Data? { try? Data(contentsOf:url(media)) }
    func remove(_ media: AutomationMediaAttachment?) { guard let media else{return}; try? fm.removeItem(at:url(media)) }
}

enum AutomationKeychain {
    private static let service="com.nextsolution.nextreminder.automations", account="scheduler-api-key"
    static func save(_ value:String) throws { let q:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account]; SecItemDelete(q as CFDictionary); var i=q; i[kSecValueData as String]=Data(value.utf8); i[kSecAttrAccessible as String]=kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly; guard SecItemAdd(i as CFDictionary,nil)==errSecSuccess else { throw AutomationError.secureStorage } }
    static func load()->String { let q:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account,kSecReturnData as String:true,kSecMatchLimit as String:kSecMatchLimitOne]; var r:CFTypeRef?; guard SecItemCopyMatching(q as CFDictionary,&r)==errSecSuccess,let d=r as? Data else{return ""}; return String(data:d,encoding:.utf8) ?? "" }
    static func remove(){ let q:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account]; SecItemDelete(q as CFDictionary) }
}

enum AutomationError: LocalizedError { case invalidEndpoint, server(String), invalidResponse, mediaTooLarge, secureStorage; var errorDescription:String? { switch self { case .invalidEndpoint:return "Enter a valid HTTPS automation server address."; case .server(let s):return s; case .invalidResponse:return "The automation server returned an invalid response."; case .mediaTooLarge:return "The image is larger than 10 MB."; case .secureStorage:return "The secure API key could not be saved." } } }

struct AutomationCloudClient {
    struct Response:Decodable { var id:String?; var message:String? }
    struct Payload:Encodable { var localID:String; var remoteJobID:String?; var platform:String; var mode:String; var scheduledAt:String; var timeZone:String; var repeatRule:String; var accountType:String?; var remoteAccountID:String?; var recipient:String; var text:String; var altText:String; var linkURL:String; var retryEnabled:Bool; var maxRetries:Int; var mediaMimeType:String?; var mediaBase64:String?; var publishNow:Bool }
    func test(_ c:AutomationCloudConfiguration) async throws -> String { let r=try request(c,"v1/health","GET"); let (d,u)=try await URLSession.shared.data(for:r); try validate(u,d); return (try? JSONDecoder().decode(Response.self,from:d).message) ?? "Connection successful" }
    func submit(_ a:SocialAutomation,account:AutomationAccount?,media:Data?,configuration c:AutomationCloudConfiguration,publishNow:Bool) async throws -> String { if let media,media.count>10_000_000 { throw AutomationError.mediaTooLarge }; var r=try request(c,publishNow ? "v1/automations/publish":"v1/automations","POST"); r.setValue("application/json",forHTTPHeaderField:"Content-Type"); let f=ISO8601DateFormatter(); r.httpBody=try JSONEncoder().encode(Payload(localID:a.id.uuidString,remoteJobID:a.remoteJobID,platform:a.platform.rawValue,mode:a.deliveryMode.rawValue,scheduledAt:f.string(from:a.scheduledAt),timeZone:a.timeZoneIdentifier,repeatRule:a.repeatRule.rawValue,accountType:account?.accountType.rawValue,remoteAccountID:account?.remoteAccountID,recipient:a.recipient,text:a.contentText,altText:a.altText,linkURL:a.linkURL,retryEnabled:a.retryEnabled,maxRetries:a.maxRetries,mediaMimeType:a.media?.mimeType,mediaBase64:media?.base64EncodedString(),publishNow:publishNow)); let (d,u)=try await URLSession.shared.data(for:r); try validate(u,d); let x=try JSONDecoder().decode(Response.self,from:d); guard let id=x.id ?? a.remoteJobID else { throw AutomationError.invalidResponse }; return id }
    private func request(_ c:AutomationCloudConfiguration,_ path:String,_ method:String)throws->URLRequest { guard c.isConfigured,let base=URL(string:c.endpoint),let url=URL(string:path,relativeTo:base.appendingPathComponent("/"))?.absoluteURL else { throw AutomationError.invalidEndpoint }; var r=URLRequest(url:url); r.httpMethod=method; r.timeoutInterval=30; r.setValue("Bearer \(c.apiKey)",forHTTPHeaderField:"Authorization"); r.setValue("NextReminder-iOS/1.1",forHTTPHeaderField:"User-Agent"); return r }
    private func validate(_ response:URLResponse,_ data:Data)throws { guard let h=response as? HTTPURLResponse else { throw AutomationError.invalidResponse }; guard (200...299).contains(h.statusCode) else { let m=(try? JSONDecoder().decode(Response.self,from:data).message) ?? "Server request failed (\(h.statusCode))."; throw AutomationError.server(m) } }
}

struct PendingAutomationAction:Codable { enum Kind:String,Codable { case open,skip }; var automationID:UUID; var kind:Kind }
extension Notification.Name { static let nextAutomationAction = Notification.Name("nextAutomationAction") }
final class AutomationActionCoordinator { static let shared=AutomationActionCoordinator(); private let key="NextReminder.PendingAutomationAction"; private init(){}; func store(_ a:PendingAutomationAction){ if let d=try? JSONEncoder().encode(a){UserDefaults.standard.set(d,forKey:key)}; NotificationCenter.default.post(name:.nextAutomationAction,object:nil) }; func consume()->PendingAutomationAction?{ guard let d=UserDefaults.standard.data(forKey:key),let a=try? JSONDecoder().decode(PendingAutomationAction.self,from:d) else{return nil}; UserDefaults.standard.removeObject(forKey:key); return a } }

final class AutomationNotificationCenter {
    static let shared=AutomationNotificationCenter(); static let category="NEXT_AUTOMATION_CATEGORY",openAction="NEXT_AUTOMATION_OPEN",skipAction="NEXT_AUTOMATION_SKIP"; private let center=UNUserNotificationCenter.current(); private init(){}
    func install(){ let complete=UNTextInputNotificationAction(identifier:NotificationManager.completeActionIdentifier,title:"Complete with Comment",options:[],textInputButtonTitle:"Complete",textInputPlaceholder:"Optional completion comment"); let snooze=UNNotificationAction(identifier:NotificationManager.snoozeActionIdentifier,title:"Snooze 10 Minutes",options:[]); let rc=UNNotificationCategory(identifier:NotificationManager.categoryIdentifier,actions:[complete,snooze],intentIdentifiers:[],options:[.customDismissAction]); let open=UNNotificationAction(identifier:Self.openAction,title:"Review & Publish",options:[.foreground]); let skip=UNNotificationAction(identifier:Self.skipAction,title:"Skip",options:[.destructive]); let ac=UNNotificationCategory(identifier:Self.category,actions:[open,skip],intentIdentifiers:[],options:[.customDismissAction]); center.setNotificationCategories([rc,ac]) }
    func schedule(_ a:SocialAutomation) async { await cancel(a.id); guard a.status != .paused,!a.status.isFinished else{return}; for o in a.alertOffsets { let date=a.scheduledAt.addingTimeInterval(-o.seconds); guard date>Date() else{continue}; let c=UNMutableNotificationContent(); c.title=a.title; c.subtitle=a.deliveryMode == .automaticCloud ? "Automatic \(a.platform.shortTitle) job":"\(a.platform.shortTitle) automation is ready"; c.body=a.deliveryMode == .automaticCloud ? "Open Next Reminder to check the cloud publishing status.":"Review the prepared content and publish or send it."; c.sound = .default; c.categoryIdentifier=Self.category; c.threadIdentifier="automations"; c.interruptionLevel = .timeSensitive; c.userInfo=["automationID":a.id.uuidString]; let parts=Calendar.current.dateComponents([.year,.month,.day,.hour,.minute,.second],from:date); let t=UNCalendarNotificationTrigger(dateMatching:parts,repeats:false); try? await center.add(.init(identifier:"automation-\(a.id.uuidString)-\(o.rawValue)",content:c,trigger:t)) } }
    func cancel(_ id:UUID) async { let p="automation-\(id.uuidString)"; let r=await center.pendingNotificationRequests(); let ids=r.map(\.identifier).filter{$0.hasPrefix(p)}; center.removePendingNotificationRequests(withIdentifiers:ids); center.removeDeliveredNotifications(withIdentifiers:ids) }
}

@MainActor final class AutomationStore:ObservableObject {
    @Published private(set) var automations:[SocialAutomation]=[]; @Published private(set) var accounts:[AutomationAccount]=[]; @Published var lastErrorMessage:String?; @Published var requestedAutomationID:UUID?; @Published var connectionMessage:String?; @Published var isTesting=false
    private let disk=AutomationPersistence(), cloud=AutomationCloudClient(); private var bag=Set<AnyCancellable>(); private let endpointKey="NextReminder.AutomationCloudEndpoint"; private static let queue=DispatchQueue(label:"com.nextsolution.nextreminder.automations",qos:.utility)
    init(){ do { let d=try disk.load(); automations=d.automations; accounts=d.accounts } catch { lastErrorMessage="Could not load saved automations." }; NotificationCenter.default.publisher(for:.nextAutomationAction).receive(on:RunLoop.main).sink{[weak self]_ in self?.processAction()}.store(in:&bag); processAction(); refreshDueStatuses() }
    var cloudEndpoint:String{UserDefaults.standard.string(forKey:endpointKey) ?? ""}; var cloudAPIKey:String{AutomationKeychain.load()}; var cloudConfiguration:AutomationCloudConfiguration{.init(endpoint:cloudEndpoint,apiKey:cloudAPIKey)}
    var active:[SocialAutomation]{automations.filter{!$0.status.isFinished}.sorted{$0.scheduledAt<$1.scheduledAt}}
    func automation(_ id:UUID)->SocialAutomation?{automations.first{$0.id==id}}; func account(_ id:UUID?)->AutomationAccount?{guard let id else{return nil}; return accounts.first{$0.id==id}}; func compatible(_ p:AutomationPlatform)->[AutomationAccount]{accounts.filter{$0.accountType.supports(p)}}
    func saveCloud(endpoint:String,key:String){UserDefaults.standard.set(endpoint.trimmingCharacters(in:.whitespacesAndNewlines),forKey:endpointKey); do{ if key.isEmpty{AutomationKeychain.remove()}else{try AutomationKeychain.save(key)}; connectionMessage="Configuration saved securely." }catch{lastErrorMessage=error.localizedDescription} }
    func testCloud(endpoint:String,key:String)async{isTesting=true;defer{isTesting=false};do{connectionMessage=try await cloud.test(.init(endpoint:endpoint,apiKey:key))}catch{connectionMessage=error.localizedDescription}}
    func addAccount(_ a:AutomationAccount){accounts.append(a);save()}; func updateAccount(_ a:AutomationAccount){guard let i=accounts.firstIndex(where:{$0.id==a.id})else{return};accounts[i]=a;save()}; func deleteAccount(_ a:AutomationAccount){for i in automations.indices where automations[i].accountID==a.id{automations[i].accountID=nil;automations[i].status = automations[i].deliveryMode == .automaticCloud ? .needsSetup:automations[i].status};accounts.removeAll{$0.id==a.id};save()}
    func add(_ a:SocialAutomation,image:Data?){var x=a;if let image{x.media=try? disk.saveImage(image)};prepare(&x);x.history.append(.init(date:Date(),status:x.status,comment:"Automation created"));automations.append(x);schedule(x)}
    func update(_ a:SocialAutomation,image:Data?,removeMedia:Bool){guard let i=automations.firstIndex(where:{$0.id==a.id})else{return};var x=a;let old=automations[i].media;if removeMedia{disk.remove(old);x.media=nil};if let image{disk.remove(old);x.media=try? disk.saveImage(image)};x.updatedAt=Date();prepare(&x);x.history.append(.init(date:Date(),status:x.status,comment:"Automation updated"));automations[i]=x;schedule(x)}
    func delete(_ a:SocialAutomation){automations.removeAll{$0.id==a.id};disk.remove(a.media);save();Task{await AutomationNotificationCenter.shared.cancel(a.id)}}
    func duplicate(_ a:SocialAutomation){var x=a;x.id=UUID();x.title+=" Copy";x.scheduledAt=max(Date().addingTimeInterval(3600),a.scheduledAt.addingTimeInterval(3600));x.status=.scheduled;x.remoteJobID=nil;x.completedAt=nil;x.lastError=nil;x.retryCount=0;x.createdAt=Date();x.updatedAt=Date();x.history=[.init(date:Date(),status:.scheduled,comment:"Duplicated")];if let m=a.media,let d=disk.data(m){x.media=try? disk.saveImage(d)};automations.append(x);schedule(x)}
    func pause(_ a:SocialAutomation){change(a.id){$0.status=.paused;$0.history.append(.init(date:Date(),status:.paused,comment:"Paused"))};Task{await AutomationNotificationCenter.shared.cancel(a.id)}};func resume(_ a:SocialAutomation){change(a.id){$0.status=$0.scheduledAt<=Date() ? .awaitingApproval:.scheduled};if let x=automation(a.id){schedule(x)}};func skip(_ a:SocialAutomation){finish(a,.skipped,"Skipped")};func markAssistedComplete(_ a:SocialAutomation){finish(a,a.platform == .whatsapp ? .sent:.published,"Confirmed after assisted publishing")}
    func submit(_ a:SocialAutomation,publishNow:Bool=false)async{guard let i=automations.firstIndex(where:{$0.id==a.id})else{return};guard cloudConfiguration.isConfigured else{automations[i].status=.needsSetup;automations[i].lastError="Connect an HTTPS scheduler in Settings.";save();return};guard let acc=account(a.accountID),acc.isReadyForAutomaticPublishing,acc.accountType.supports(a.platform)else{automations[i].status=.needsSetup;automations[i].lastError="Select a compatible automatic account.";save();return};automations[i].status=.processing;save();do{let d=a.media.flatMap{disk.data($0)};let id=try await cloud.submit(automations[i],account:acc,media:d,configuration:cloudConfiguration,publishNow:publishNow);automations[i].remoteJobID=id;if publishNow{finishAt(i,a.platform == .whatsapp ? .sent:.published,"Cloud publisher accepted the request")}else{automations[i].status=.scheduled;automations[i].history.append(.init(date:Date(),status:.scheduled,comment:"Cloud schedule accepted"));save()}}catch{automations[i].status=.failed;automations[i].lastError=error.localizedDescription;automations[i].retryCount+=1;automations[i].history.append(.init(date:Date(),status:.failed,comment:error.localizedDescription));save()}}
    func mediaURL(_ a:SocialAutomation)->URL?{a.media.map{disk.url($0)}};func mediaData(_ a:SocialAutomation)->Data?{a.media.flatMap{disk.data($0)}}
    func refreshDueStatuses(){var dirty=false;for i in automations.indices where automations[i].status == .scheduled && automations[i].scheduledAt<=Date() && automations[i].deliveryMode != .automaticCloud{automations[i].status=.awaitingApproval;automations[i].history.append(.init(date:Date(),status:.awaitingApproval,comment:"Scheduled time arrived"));dirty=true};if dirty{save()}}
    func clearRequested(){requestedAutomationID=nil}
    private func prepare(_ x:inout SocialAutomation){if x.deliveryMode == .automaticCloud{let a=account(x.accountID);x.status=cloudConfiguration.isConfigured && a?.isReadyForAutomaticPublishing == true ? .scheduled:.needsSetup}else{x.status=x.scheduledAt<=Date() ? .awaitingApproval:.scheduled};x.lastError=x.status == .needsSetup ? "Complete automatic publishing setup.":nil}
    private func schedule(_ a:SocialAutomation){save();Task{await AutomationNotificationCenter.shared.schedule(a);if a.deliveryMode == .automaticCloud{await submit(a)}}}
    private func finish(_ a:SocialAutomation,_ s:AutomationStatus,_ c:String){guard let i=automations.firstIndex(where:{$0.id==a.id})else{return};finishAt(i,s,c)}
    private func finishAt(_ i:Int,_ s:AutomationStatus,_ c:String){let old=automations[i];automations[i].status=s;automations[i].completedAt=Date();automations[i].updatedAt=Date();automations[i].history.append(.init(date:Date(),status:s,comment:c));Task{await AutomationNotificationCenter.shared.cancel(old.id)};if let next=old.repeatRule.nextDate(after:old.scheduledAt),s != .skipped{var n=old;n.id=UUID();n.scheduledAt=next;n.status=.scheduled;n.remoteJobID=nil;n.completedAt=nil;n.retryCount=0;n.createdAt=Date();n.updatedAt=Date();n.history=[.init(date:Date(),status:.scheduled,comment:"Next recurring automation")];if let m=old.media,let d=disk.data(m){n.media=try? disk.saveImage(d)};automations.append(n);schedule(n)};save()}
    private func change(_ id:UUID,_ f:(inout SocialAutomation)->Void){guard let i=automations.firstIndex(where:{$0.id==id})else{return};f(&automations[i]);automations[i].updatedAt=Date();save()}
    private func save(){let d=AutomationDatabase(automations:automations,accounts:accounts),disk=self.disk;Self.queue.async{try? disk.save(d)}}
    private func processAction(){guard let a=AutomationActionCoordinator.shared.consume(),let x=automation(a.automationID)else{return};if a.kind == .skip{skip(x)}else{refreshDueStatuses();requestedAutomationID=x.id}}
}

@MainActor enum AssistedAutomationPublisher { static func text(_ a:SocialAutomation)->String{[a.contentText,a.linkURL].map{$0.trimmingCharacters(in:.whitespacesAndNewlines)}.filter{!$0.isEmpty}.joined(separator:"\n\n")};static func url(_ a:SocialAutomation)->URL?{let e=text(a).addingPercentEncoding(withAllowedCharacters:.urlQueryAllowed) ?? "";if a.platform == .whatsapp && a.media == nil{return URL(string:"https://wa.me/\(a.recipient.filter(\.isNumber))?text=\(e)")};if a.platform == .xPost && a.media == nil{return URL(string:"https://twitter.com/intent/tweet?text=\(e)")};return nil};static func items(_ a:SocialAutomation,media:Data?)->[Any]{var x:[Any]=[];if let media,let i=UIImage(data:media){x.append(i)};let t=text(a);if !t.isEmpty{x.append(t)};return x} }
