#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "NextReminder" / "Sources"


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    if old not in text:
        raise SystemExit(f"Expected text not found in {path}: {old[:320]!r}")
    path.write_text(text.replace(old, new, 1))


# Handle quick-reminder URLs generated by the RootHide SpringBoard panel.
app = SOURCES / "App.swift"
app_text = app.read_text()
if "QuickReminderImporter.handle" not in app_text:
    replace_once(
        app,
        '''                .onChange(of: scenePhase) { phase in''',
        '''                .onOpenURL { url in
                    Task { await QuickReminderImporter.handle(url, store: store) }
                }
                .onChange(of: scenePhase) { phase in'''
    )

# Show a clear import result after the app receives the quick-add URL.
root = SOURCES / "RootReminders.swift"
root_text = root.read_text()
if "quickReminderImportMessage" not in root_text:
    replace_once(
        root,
        '''    @State private var openedEmailReminder: IdentifiedReminderID?''',
        '''    @State private var openedEmailReminder: IdentifiedReminderID?
    @State private var quickReminderImportMessage: String?'''
    )
    replace_once(
        root,
        '''        .confirmationDialog(
            "What would you like to create?",''',
        '''        .onReceive(NotificationCenter.default.publisher(for: .nextQuickReminderImportResult)) { notification in
            quickReminderImportMessage = notification.object as? String
            selectedTab = .reminders
        }
        .alert("Quick Reminder", isPresented: Binding(
            get: { quickReminderImportMessage != nil },
            set: { if !$0 { quickReminderImportMessage = nil } }
        )) {
            Button("OK", role: .cancel) { quickReminderImportMessage = nil }
        } message: {
            Text(quickReminderImportMessage ?? "Quick reminder processed.")
        }
        .confirmationDialog(
            "What would you like to create?",'''
    )

# Version metadata.
project = ROOT / "project.yml"
project_text = project.read_text()
project_text = project_text.replace('CFBundleShortVersionString: "1.3.12"', 'CFBundleShortVersionString: "1.3.13"')
project_text = project_text.replace('CFBundleVersion: "22"', 'CFBundleVersion: "23"')
project_text = project_text.replace('MARKETING_VERSION: "1.3.12"', 'MARKETING_VERSION: "1.3.13"')
project_text = project_text.replace('CURRENT_PROJECT_VERSION: "22"', 'CURRENT_PROJECT_VERSION: "23"')
project.write_text(project_text)

settings = SOURCES / "Settings.swift"
settings.write_text(
    settings.read_text().replace(
        "Version 1.3.12 • iOS 16.0+",
        "Version 1.3.13 • iOS 16.0+"
    )
)

for path in SOURCES.glob("*.swift"):
    path.write_text(
        path.read_text().replace(
            "NextReminder-iOS/1.3.12",
            "NextReminder-iOS/1.3.13"
        )
    )

print("Next Reminder v1.3.13 quick gesture importer applied successfully.")
