name: NextPDF
options:
  bundleIdPrefix: com.nextsolution
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.nextsolution.nextpdf
    SWIFT_VERSION: 5.9
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  NextPDF:
    type: application
    platform: iOS
    sources:
      - NextPDF
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: Next PDF
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_LSSupportsOpeningDocumentsInPlace: YES
        INFOPLIST_KEY_UIFileSharingEnabled: YES
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: NO
    scheme:
      testTargets: []
