include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = BrightnessEdgeHapticPreferences
BrightnessEdgeHapticPreferences_FILES = BEHRootListController.m
BrightnessEdgeHapticPreferences_FRAMEWORKS = UIKit
BrightnessEdgeHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
BrightnessEdgeHapticPreferences_RESOURCE_DIRS = Resources
BrightnessEdgeHapticPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
BrightnessEdgeHapticPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000
include $(THEOS_MAKE_PATH)/bundle.mk
