include $(THEOS)/makefiles/common.mk
BUNDLE_NAME = BrightnessEdgeHapticPreferences
BrightnessEdgeHapticPreferences_FILES = BEHRootListController.m
BrightnessEdgeHapticPreferences_FRAMEWORKS = UIKit
BrightnessEdgeHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
BrightnessEdgeHapticPreferences_RESOURCE_DIRS = Resources
BrightnessEdgeHapticPreferences_CFLAGS = -fobjc-arc
include $(THEOS_MAKE_PATH)/bundle.mk
