include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LockGlyphTimePrefs
LockGlyphTimePrefs_FILES = LGTListControllerV023.m
LockGlyphTimePrefs_FRAMEWORKS = UIKit PhotosUI
LockGlyphTimePrefs_INSTALL_PATH = /Library/PreferenceBundles
LockGlyphTimePrefs_RESOURCE_DIRS = Resources
LockGlyphTimePrefs_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
LockGlyphTimePrefs_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk