include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LockGlyphTimePrefs
LockGlyphTimePrefs_FILES = LGTListController.m
LockGlyphTimePrefs_FRAMEWORKS = UIKit
LockGlyphTimePrefs_PRIVATE_FRAMEWORKS = Preferences
LockGlyphTimePrefs_INSTALL_PATH = /Library/PreferenceBundles
LockGlyphTimePrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
