include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = InternetLostHapticPreferences
InternetLostHapticPreferences_FILES = ILHRootListController.m
InternetLostHapticPreferences_FRAMEWORKS = UIKit
InternetLostHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
InternetLostHapticPreferences_RESOURCE_DIRS = Resources
InternetLostHapticPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
InternetLostHapticPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
