include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = HeadphoneDisconnectHapticPreferences
HeadphoneDisconnectHapticPreferences_FILES = HDHRootListController.m
HeadphoneDisconnectHapticPreferences_FRAMEWORKS = UIKit
HeadphoneDisconnectHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
HeadphoneDisconnectHapticPreferences_RESOURCE_DIRS = Resources
HeadphoneDisconnectHapticPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
HeadphoneDisconnectHapticPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
