include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = HeadphoneDisconnectHapticPreferences
HeadphoneDisconnectHapticPreferences_FILES = HDHRootListController.m
HeadphoneDisconnectHapticPreferences_FRAMEWORKS = UIKit
HeadphoneDisconnectHapticPreferences_PRIVATE_FRAMEWORKS = Preferences
HeadphoneDisconnectHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
HeadphoneDisconnectHapticPreferences_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
