include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Charge80HapticPreferences
Charge80HapticPreferences_FILES = C80RootListController.m
Charge80HapticPreferences_FRAMEWORKS = UIKit
Charge80HapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
Charge80HapticPreferences_RESOURCE_DIRS = Resources
Charge80HapticPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
Charge80HapticPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
