include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CleanHomeLabelsPreferences
CleanHomeLabelsPreferences_FILES = CHLRootListController.m
CleanHomeLabelsPreferences_FRAMEWORKS = UIKit
CleanHomeLabelsPreferences_INSTALL_PATH = /Library/PreferenceBundles
CleanHomeLabelsPreferences_RESOURCE_DIRS = Resources
CleanHomeLabelsPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
CleanHomeLabelsPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
