include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ScreenRecordingHapticAlertPreferences
ScreenRecordingHapticAlertPreferences_FILES = SRHRootListController.m
ScreenRecordingHapticAlertPreferences_FRAMEWORKS = UIKit
ScreenRecordingHapticAlertPreferences_INSTALL_PATH = /Library/PreferenceBundles
ScreenRecordingHapticAlertPreferences_RESOURCE_DIRS = Resources
ScreenRecordingHapticAlertPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
ScreenRecordingHapticAlertPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
