name: NextSigner
options:
  bundleIdPrefix: com.nextsolution
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
packages:
  Sodium:
    url: https://github.com/jedisct1/swift-sodium.git
    exactVersion: 0.11.0
settings:
  base:
    SWIFT_VERSION: "5.7"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: "NO"
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.3.8"
    CURRENT_PROJECT_VERSION: "21"
targets:
  NextSigner:
    type: application
    platform: iOS
    sources:
      - path: NextSigner
    dependencies:
      - package: Sodium
    preBuildScripts:
      - name: Generate Next Signer App Icon
        basedOnDependencyAnalysis: false
        script: |
          python3 "$SRCROOT/generate_app_icon.py"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nextsolution.nextsigner
        PRODUCT_NAME: Next Signer
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_CFBundleDisplayName: Next Signer
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UIFileSharingEnabled: "YES"
        INFOPLIST_KEY_LSSupportsOpeningDocumentsInPlace: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      shared: true
      gatherCoverageData: false
