include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = NextHomeTorchPreferences
NextHomeTorchPreferences_FILES = NHTRootListController.m
NextHomeTorchPreferences_FRAMEWORKS = UIKit
NextHomeTorchPreferences_INSTALL_PATH = /Library/PreferenceBundles
NextHomeTorchPreferences_RESOURCE_DIRS = Resources
NextHomeTorchPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
NextHomeTorchPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
