include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ThermalWarningHapticPreferences
ThermalWarningHapticPreferences_FILES = TWHRootListController.m
ThermalWarningHapticPreferences_FRAMEWORKS = UIKit
ThermalWarningHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
ThermalWarningHapticPreferences_RESOURCE_DIRS = Resources
ThermalWarningHapticPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
ThermalWarningHapticPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
