include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LowPowerModeHapticPreferences
LowPowerModeHapticPreferences_FILES = LPMHRootListController.m
LowPowerModeHapticPreferences_FRAMEWORKS = UIKit
LowPowerModeHapticPreferences_INSTALL_PATH = /Library/PreferenceBundles
LowPowerModeHapticPreferences_RESOURCE_DIRS = Resources
LowPowerModeHapticPreferences_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
LowPowerModeHapticPreferences_LDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-segalign,4000

include $(THEOS_MAKE_PATH)/bundle.mk
