name: NextPost
options:
  bundleIdPrefix: com.nextsolution
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

packages:
  LevelPlay:
    url: https://github.com/ironsource-mobile/LevelPlay-Swift-Package
    branch: main

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: "NO"
    CODE_SIGN_STYLE: Manual
    MARKETING_VERSION: "1.0.5"
    CURRENT_PROJECT_VERSION: "5"
    OTHER_LDFLAGS: "$(inherited) -ObjC"

targets:
  NextPost:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
        buildPhase: resources
      - path: PrivacyInfo.xcprivacy
        buildPhase: resources
    dependencies:
      - package: LevelPlay
        product: UnityMediationSDK
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nextsolution.nextpost
        PRODUCT_NAME: Next Post
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: "NO"
    scheme:
      shared: true
      gatherCoverageData: false
