from pathlib import Path

p = Path('buildsrc/Runtime/Tweak.m')
s = p.read_text()

def rep(old, new):
    global s
    assert old in s, old[:120]
    s = s.replace(old, new, 1)

rep('''static NSHashTable *MGControllers;\nstatic char MGLastDiagnosticKey;''', '''static NSHashTable *MGControllers;\n// While any Control Center module is transitioning, all Module Glass renderers\n// are quarantined. Some Apple modules expand through a parent controller while\n// their customized child controller continues receiving layout/value callbacks.\n// A process-wide gate prevents those child callbacks from mutating the live\n// hierarchy until Apple's transition has completed.\nstatic BOOL MGGlobalTransitionQuarantine = NO;\nstatic NSUInteger MGGlobalTransitionGeneration = 0;\nstatic char MGLastDiagnosticKey;''')

rep('''static void MGLabelSetText(UILabel *label, SEL _cmd, NSString *text) {\n    if (MGOrigLabelSetText) MGOrigLabelSetText(label, _cmd, text);\n    UIColor *custom=objc_getAssociatedObject(label, &MGVolumePercentageColorKey);''', '''static void MGLabelSetText(UILabel *label, SEL _cmd, NSString *text) {\n    if (MGOrigLabelSetText) MGOrigLabelSetText(label, _cmd, text);\n    if (MGGlobalTransitionQuarantine) return;\n    UIColor *custom=objc_getAssociatedObject(label, &MGVolumePercentageColorKey);''')

rep('''static void MGLabelSetAttributedText(UILabel *label, SEL _cmd, NSAttributedString *text) {\n    UIColor *custom=objc_getAssociatedObject(label, &MGVolumePercentageColorKey);''', '''static void MGLabelSetAttributedText(UILabel *label, SEL _cmd, NSAttributedString *text) {\n    if (MGGlobalTransitionQuarantine) {\n        if (MGOrigLabelSetAttributedText) MGOrigLabelSetAttributedText(label, _cmd, text);\n        return;\n    }\n    UIColor *custom=objc_getAssociatedObject(label, &MGVolumePercentageColorKey);''')

rep('''static void MGLabelSetTextColor(UILabel *label, SEL _cmd, UIColor *color) {\n    UIColor *custom=objc_getAssociatedObject(label, &MGVolumePercentageColorKey);''', '''static void MGLabelSetTextColor(UILabel *label, SEL _cmd, UIColor *color) {\n    if (MGGlobalTransitionQuarantine) {\n        if (MGOrigLabelSetTextColor) MGOrigLabelSetTextColor(label, _cmd, color);\n        return;\n    }\n    UIColor *custom=objc_getAssociatedObject(label, &MGVolumePercentageColorKey);''')

rep('''static void MGSliderSetValue(id self, SEL _cmd, CGFloat value) {\n    if (MGOrigSliderSetValue) MGOrigSliderSetValue(self, _cmd, value);\n    if (![self isKindOfClass:UIView.class]) return;''', '''static void MGSliderSetValue(id self, SEL _cmd, CGFloat value) {\n    if (MGOrigSliderSetValue) MGOrigSliderSetValue(self, _cmd, value);\n    // Never touch our image mask while Apple is animating an expansion/collapse.\n    // Volume can keep receiving value updates from a child controller even when\n    // the parent container owns the actual expansion transition.\n    if (MGGlobalTransitionQuarantine) return;\n    if (![self isKindOfClass:UIView.class]) return;''')

rep('''    MGSetTaggedImagesHiddenRecursive(root, YES);\n    MGRestoreVolumeColorPresentation(root);''', '''    MGSetTaggedImagesHiddenRecursive(root, YES);\n    UIView *slider = MGFindSliderView(root);\n    if (slider) objc_setAssociatedObject(slider, &MGVolumeFillImageKey, nil, OBJC_ASSOCIATION_RETAIN_NONATOMIC);\n    MGRestoreVolumeColorPresentation(root);''')

anchor = '''static BOOL MGExpansionSuspended(id controller) {'''
insert = '''static void MGQuarantineAllTrackedControllers(NSString *source) {\n    NSArray *controllers = nil;\n    @synchronized (MGControllers) { controllers = MGControllers.allObjects; }\n    for (id controller in controllers) {\n        if (!controller || ![controller respondsToSelector:@selector(view)]) continue;\n        MGSuspendControllerVisualsNonDestructive(controller, source);\n    }\n    if (MGVerboseDiagnosticsEnabled()) MGLog(@"transition-global-quarantine source=%@ controllers=%lu generation=%lu", source?:@"<nil>", (unsigned long)controllers.count, (unsigned long)MGGlobalTransitionGeneration);\n}\n\n'''
assert anchor in s
s = s.replace(anchor, insert + anchor, 1)

rep('''    UIView *root = [controller view];\n    if (!root) return;\n\n    if (MGExpansionSuspended(controller)) return;''', '''    UIView *root = [controller view];\n    if (!root) return;\n\n    // Parent and child CC controllers do not always receive the same expansion\n    // callback. The global gate is intentionally checked before any restore,\n    // traversal, insertion, masking, or suppression work.\n    if (MGGlobalTransitionQuarantine) return;\n    if (MGExpansionSuspended(controller)) return;''')

rep('''static void MGRefreshAll(NSString *source, BOOL forceReloadImages) {\n    dispatch_async(dispatch_get_main_queue(), ^{\n        NSArray *controllers = nil;''', '''static void MGRefreshAll(NSString *source, BOOL forceReloadImages) {\n    dispatch_async(dispatch_get_main_queue(), ^{\n        if (MGGlobalTransitionQuarantine) {\n            if (MGVerboseDiagnosticsEnabled()) MGLog(@"refresh-deferred-transition-quarantine source=%@", source?:@"<nil>");\n            return;\n        }\n        NSArray *controllers = nil;''')

anchor = '''static void MGFinishTransition(id controller, NSUInteger generation, NSString *source) {'''
insert = '''static void MGFinishGlobalTransition(NSUInteger globalGeneration, NSString *source) {\n    if (globalGeneration != MGGlobalTransitionGeneration) return;\n    MGGlobalTransitionQuarantine = NO;\n    if (MGVerboseDiagnosticsEnabled()) MGLog(@"transition-global-resume source=%@ generation=%lu", source?:@"<nil>", (unsigned long)globalGeneration);\n    MGRefreshAll(source ?: @"transition-global-resume", NO);\n}\n\nstatic void MGScheduleGlobalTransitionWatchdog(id controller, NSUInteger globalGeneration, NSString *source) {\n    __weak id weakController = controller;\n    dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(2.0*NSEC_PER_SEC)),dispatch_get_main_queue(),^{\n        if (!MGGlobalTransitionQuarantine || globalGeneration != MGGlobalTransitionGeneration) return;\n        id strongController = weakController;\n        if (strongController && MGHasTransitionCoordinator(strongController)) return;\n        if (MGVerboseDiagnosticsEnabled()) MGLog(@"transition-global-watchdog source=%@ generation=%lu", source?:@"<nil>", (unsigned long)globalGeneration);\n        MGFinishGlobalTransition(globalGeneration, @"transition-global-watchdog");\n    });\n}\n\n'''
assert anchor in s
s = s.replace(anchor, insert + anchor, 1)

rep('''static void MGRegisterTransitionCompletion(id controller, id coordinator, NSUInteger generation, NSString *source) {\n    __weak id weakController=controller;\n    if (coordinator && [coordinator respondsToSelector:@selector(animateAlongsideTransition:completion:)]) {\n        [coordinator animateAlongsideTransition:nil completion:^(__unused id context){\n            id strongController=weakController;\n            if (strongController) MGFinishTransition(strongController,generation,source);\n        }];\n    } else {\n        dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(0.55*NSEC_PER_SEC)),dispatch_get_main_queue(),^{\n            id strongController=weakController;\n            if (strongController) MGFinishTransition(strongController,generation,source);\n        });\n    }\n    MGTransitionWatchdog(controller,generation,source);\n}''', '''static void MGRegisterTransitionCompletion(id controller, id coordinator, NSUInteger generation, NSUInteger globalGeneration, NSString *source) {\n    __weak id weakController=controller;\n    if (coordinator && [coordinator respondsToSelector:@selector(animateAlongsideTransition:completion:)]) {\n        [coordinator animateAlongsideTransition:nil completion:^(__unused id context){\n            id strongController=weakController;\n            if (strongController) MGFinishTransition(strongController,generation,source);\n            MGFinishGlobalTransition(globalGeneration,source);\n        }];\n    } else {\n        dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(0.55*NSEC_PER_SEC)),dispatch_get_main_queue(),^{\n            id strongController=weakController;\n            if (strongController) MGFinishTransition(strongController,generation,source);\n            MGFinishGlobalTransition(globalGeneration,source);\n        });\n    }\n    MGTransitionWatchdog(controller,generation,source);\n    MGScheduleGlobalTransitionWatchdog(controller,globalGeneration,source);\n}''')

rep('''static void MGHandleWillTransition(id controller, CGSize size, id coordinator, NSString *source) {\n    if (!controller) return;\n    NSUInteger generation=MGAdvanceExpansionGeneration(controller);\n    MGSetExpansionTransitionActive(controller,YES);\n    // Suspend for both directions without changing the UIKit hierarchy. On expand we\n    // hide custom presentation in place; on collapse we keep the renderer passive\n    // until compact geometry is stable.\n    MGBeginExpansionSuspension(controller,source);\n    if (MGVerboseDiagnosticsEnabled()) MGLog(@"transition-begin source=%@ controller=%@ target=%@ generation=%lu",source?:@"<nil>",NSStringFromClass([controller class]),NSStringFromCGSize(size),(unsigned long)generation);\n    MGRegisterTransitionCompletion(controller,coordinator,generation,[source stringByAppendingString:@"-complete"]);\n}''', '''static void MGHandleWillTransition(id controller, CGSize size, id coordinator, NSString *source) {\n    if (!controller) return;\n    NSUInteger generation=MGAdvanceExpansionGeneration(controller);\n    NSUInteger globalGeneration=++MGGlobalTransitionGeneration;\n    MGGlobalTransitionQuarantine=YES;\n    // Quarantine every tracked renderer BEFORE Apple's original transition method\n    // runs. This catches child controllers (notably Volume and Connectivity) whose\n    // layout/value callbacks can continue while a parent container owns expansion.\n    MGQuarantineAllTrackedControllers(source);\n    MGSetExpansionTransitionActive(controller,YES);\n    MGBeginExpansionSuspension(controller,source);\n    if (MGVerboseDiagnosticsEnabled()) MGLog(@"transition-begin source=%@ controller=%@ target=%@ generation=%lu globalGeneration=%lu",source?:@"<nil>",NSStringFromClass([controller class]),NSStringFromCGSize(size),(unsigned long)generation,(unsigned long)globalGeneration);\n    MGRegisterTransitionCompletion(controller,coordinator,generation,globalGeneration,[source stringByAppendingString:@"-complete"]);\n}''')

rep('ModuleGlassRuntime 1.1.13 Non-Destructive Transition Renderer loaded', 'ModuleGlassRuntime 1.1.14 Global Transition Quarantine Renderer loaded')
p.write_text(s)

c = Path('buildsrc/Runtime/control')
t = c.read_text()
repls = {
    'Version: 1.1.13':'Version: 1.1.14',
    'Description: RootHide Module Glass 1.1.13 with non-destructive expansion suspension; preserves compact renderer features while avoiding UIKit hierarchy mutation during Apple Control Center transitions.':'Description: RootHide Module Glass 1.1.14 with global Control Center transition quarantine; prevents parent/child render callbacks and Volume value-mask updates from mutating customized modules during expansion while preserving the 1.1.13 compact renderer.',
    'Provides: com.nextsolution.nextaura.runtime.ccbackgrounds (= 1.1.13)':'Provides: com.nextsolution.nextaura.runtime.ccbackgrounds (= 1.1.14)',
    'Conflicts: com.nextsolution.nextaura.runtime.ccbackgrounds (<= 1.1.12), com.nextsolution.unlockvibrate':'Conflicts: com.nextsolution.nextaura.runtime.ccbackgrounds (<= 1.1.13), com.nextsolution.unlockvibrate',
    'Breaks: com.nextsolution.nextaura.runtime.ccbackgrounds (<= 1.1.12)':'Breaks: com.nextsolution.nextaura.runtime.ccbackgrounds (<= 1.1.13)',
    'Replaces: com.nextsolution.nextaura.runtime.ccbackgrounds (<= 1.1.12)':'Replaces: com.nextsolution.nextaura.runtime.ccbackgrounds (<= 1.1.13)',
}
for old,new in repls.items():
    assert old in t, old
    t=t.replace(old,new,1)
c.write_text(t)
